#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: check_machine_room 3558 2020-05-22 18:41:08Z Alan $

########################################################################

# Copyright © 2012, 2013, 2014, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

#\
umask 0; PATH=/usr/local/opt/tcl-tk/bin:$PATH exec tclsh8.6 -encoding "utf-8" "$0" ${1+"$@"}


########################################################################

proc checktemperature {filename criticalmin warningmin warningmax criticalmax} {

  set channel [open $filename "r"]
  set line [gets $channel]
  close $channel

  if {[scan $line "%f" temperature] != 1} {
    return [list 1 "unknown"]
  }

  set temperature [format "%.1f" $temperature]

  if {$temperature < $criticalmin || $temperature > $criticalmax} {
    return [list 2 "$temperature C"]
  } elseif {$temperature < $warningmin || $temperature > $warningmax} {
    return [list 1 "$temperature C"]
  } else {
    return [list 0 "$temperature C"]
  }
}

########################################################################

# On page 30 of the technical manual for the R310, the operating
# temperature range is given as: "10° to 35°C (50° to 95°F) with a
# maximum temperature gradation of 10°C per hour (NOTE: For altitudes
# above 2950 feet, the maximum operating temperature is de-rated 1°F/550
# ft.)" Since the telescope is at 2790 meters (9150 feet), this implies
# that the operating temperature range should be 10 C to 29 C.

set temperatureresult  [checktemperature /var/ow/28.A87E8C020000/temperature 9 10 29 30]
set temperaturestatus  [lindex $temperatureresult 0]
set temperaturemessage [lindex $temperatureresult 1]

set status $temperaturestatus

switch $status {
  0 {
    set statustext "OK"
  }
  1 {
    set statustext "WARNING"
  }
  2 {
    set statustext "CRITICAL"
  }
}

puts "MACHINE_ROOM $statustext - $temperaturemessage."
exit $status
