#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: check_owfs_mount 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2016, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

line=$(mount | grep "/var/ow")
if test "$line" = "OWFS on /var/ow type fuse.OWFS (rw,nosuid,nodev,allow_other)"
then
  echo OWFS OK - /var/ow.
  exit 0
else
  echo OWFS CRITICAL - /var/ow.
  exit 2
fi
