#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

case $(hostname | sed 's/\..*//') in
transientsoan-nas)
  archivedir=/mnt/volume/archive-ratir
  ;;
*)
  archivedir=/mnt/storage/archive
  ;;
esac

pgidfile=/tmp/pull-archive.pgid
if test -f $pgidfile
then
  kill -KILL -- -$(cat $pgidfile)
fi
ps -p $$ -o "pgid=" >$pgidfile

extra_rsync_args="$@"

mkdir -p $archivedir/

case $(hostname | sed 's/\..*//') in
nas-cu)
  passwd=Fru78Mtm29
  src=rsync://archive-cu@ratir.astrosen.unam.mx/archive-cu/
  ;;
transientsoan-nas)
  passwd=Wfs71Smh12
  src=rsync://archive-en@ratir.astrossp.unam.mx/archive-en/
  ;;
esac

RSYNC_PASSWORD=$passwd \
rsync -aH $extra_rsync_args $src/log/. $archivedir/log/.

(
  cd $archivedir/log
  find . -name ".*" -type f | xargs rm -f
  find . -name "*.csv" | sort | xargs cat >../public/log.csv-$$-tmp
  mv ../public/log.csv-$$-tmp ../public/log.csv
  find . -name "*.txt" | sort | xargs cat >../public/log.txt-$$-tmp
  mv ../public/log.txt-$$-tmp ../public/log.txt
)

(
  cd $archivedir/public
  awk -F, '
  BEGIN {
    lastdate               = "";
    lastproposalidentifier = "";
    lastvisitidentifier    = "";
    lastbase               = "";
  }
  NF == 13 {
    date                  = $1;
    proposalidentifier    = $2;
    visitidentifier       = $3;
    hhmmss = substr($4, 10, 6) + 0;
    if (hhmmss > lasthhmmss + 2) {
      totalexposures += 1;
      chargedexposuretime = 0;
      if (exposuretime["C3"] != 0) {
        chargedexposuretime = exposuretime["C3"]; 
      } else if (exposuretime["C2"] != 0) {
        chargedexposuretime = exposuretime["C2"]; 
      } else if (exposuretime["C1"] != 0) {
        chargedexposuretime = exposuretime["C1"]; 
      } else if (exposuretime["C0"] != 0) {
        chargedexposuretime = exposuretime["C0"]; 
      }
      totalchargedexposuretime += chargedexposuretime;
      delete exposuretime;
    }
    lasthhmmss = hhmmss;
    if (date == "" || proposalidentifier == "" || visitidentifier == "")
      next;  
    if (proposalidentifier != lastproposalidentifier || visitidentifier != lastvisitidentifier) {
      if (lastdate != "") {
        printf("%s,%s,%s,%d,%.0f,%d,%.0f,%d,%.0f,%d,%.0f,%d,%.0f\n", \
          lastdate, lastproposalidentifier, lastvisitidentifier, \
          totalexposures, totalchargedexposuretime, \
          channelexposures["C0"], channelexposuretime["C0"], \
          channelexposures["C1"], channelexposuretime["C1"], \
          channelexposures["C2"], channelexposuretime["C2"], \
          channelexposures["C3"], channelexposuretime["C3"])
      }
      printf("%s,", date);
      totalexposures           = 0;
      totalchargedexposuretime = 0;
      delete channelexposures;
      delete channelexposuretime;
    }
    channel               = $5;
    exposuretime[channel] = $7;
    channelexposures[channel]    += 1;
    channelexposuretime[channel] += exposuretime[channel];
    lastdate               = date;
    lastproposalidentifier = proposalidentifier;
    lastvisitidentifier    = visitidentifier;
  }
  END {
    totalexposures           += 1;
    totalchargedexposuretime += chargedexposuretime;
    printf("%s,%s,%s,%d,%.0f,%d,%.0f,%d,%.0f,%d,%.0f,%d,%.0f\n", \
      lastdate, lastproposalidentifier, lastvisitidentifier, \
      totalexposures, totalchargedexposuretime, \
      channelexposures["C0"], channelexposuretime["C0"], \
      channelexposures["C1"], channelexposuretime["C1"], \
      channelexposures["C2"], channelexposuretime["C2"], \
      channelexposures["C3"], channelexposuretime["C3"])
  }
  ' log.csv |
  tee summary.csv-$$-tmp |
  awk -F, '
  {
    printf("%s %s %s %6d %4d %5d %4d %5d %4d %5d %4d %5d %4d %5d\n", \
      $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14);
  }
  ' >summary.txt-$$-tmp
  mv summary.csv-$$-tmp summary.csv
  mv summary.txt-$$-tmp summary.txt
)

RSYNC_PASSWORD=$passwd \
rsync -aH --exclude "*.fits.bz2*" $extra_rsync_args $src $archivedir

RSYNC_PASSWORD=$passwd \
rsync -aH $extra_rsync_args $src $archivedir

find $archivedir -name ".*" -type f | xargs rm -f
find $archivedir -name "*-tmp" -type f | xargs rm -f

rm -f $pgidfile
