#!/bin/sh

export PATH=/usr/local/bin:/usr/bin:/bin

if test $# == 0
then
  set -- $(date +%Y%m%d)
fi

archivedir=/mnt/storage/archive/
bindir=/mnt/storage/local/cron

for date in "$@"
do

  echo 1>&2 "$(date +%H:%M:%S:) $date: updating archive."

  # Create the log .csv files.
  echo 1>&2 "$(date +%H:%M:%S:) $date: creating log .csv file."
  mkdir -p "$archivedir/log/"
  cd "$archivedir/date/$date"
  csv="$archivedir/log/$date.csv"
  if test ! -e "$csv" || 
   test ! -z "$(find "$archivedir/date/$date" -name "*.txt" -newer "$csv")" ||
   test "$(find "$archivedir/date/$date" -name "*.txt" | wc -l)" != "$(wc -l <"$csv")"
  then
    find "$archivedir/date/$date" -name "*.txt" | 
    sh "$bindir/make-log-csv-file" >"$csv-$$-tmp"
    mv "$csv-$$-tmp" "$csv"
  fi

  find "$archivedir/log/" -name "*-tmp" | xargs rm -f

  # Create the log .txt files.
  echo 1>&2 "$(date +%H:%M:%S:) $date: creating log .txt file."
  csv="$archivedir/log/$date.csv"
  txt="$archivedir/log/$date.txt"
  if test ! -e "$txt" || test "$csv" -nt "$txt"
  then
    sh "$bindir/make-log-txt-file" <"$csv" >"$txt-$$-tmp"
    mv "$txt-$$-tmp" "$txt"
  fi
  find "$archivedir/log" -name "*-tmp" | xargs rm -f

  # Create the proposal links.
  echo 1>&2 "$(date +%H:%M:%S:) $date: creating proposal links."
  mkdir -p "$archivedir/proposal/"
  find . -mindepth 1 -maxdepth 1 -type d |
  (
    cd "$archivedir/date/$date"
    find . -print | cpio -pdlu --quiet "$archivedir/proposal/"
  )

  # Create the public links.
  (
    echo 1>&2 "$(date +%H:%M:%S:) $date: creating public links."
    mkdir -p "$archivedir/public"
    cd "$archivedir/date/$date/"
    (
      find . -name "*.fits.txt"
      find . -name "*.fits.bz2" -path "./2012A-0???/*"
    ) | cpio -pdlu --quiet "$archivedir/public"
  )

  echo 1>&2 "$(date +%H:%M:%S:) $date: finished updating archive."
  
done

echo 1>&2 $(date +%H:%M:%S:) done.
