#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: update-archive-etcdir 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

case $(hostname | sed 's/\..*//') in
transientsoan-nas)
  archivedir=/mnt/volume/archive-ratir
  ;;
*)
  archivedir=/mnt/storage/archive
  ;;
esac

etcdir=/usr/local/etc

mkdir -p $archivedir/etc

sed "
  s:$archivedir:%archivedir%:g
  s:$etcdir:%etcdir%:g
  /# start of prolog/,/# end of prolog/d
" $etcdir/rsyncd.conf >$archivedir/etc/rsyncd.conf-tmp

install -CpS -o archive -g archive -m 0644 $archivedir/etc/rsyncd.conf-tmp $archivedir/etc/rsyncd.conf
install -CpS -o archive -g archive -m 0600 $etcdir/rsyncd.secrets          $archivedir/etc/rsyncd.secrets

rm -f $archivedir/etc/rsyncd.conf-tmp
