#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: update-archive-proposalidentifiers 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

case $(hostname | sed 's/\..*//') in
transientsoan-nas)
  archivedir=/mnt/volume/archive-ratir
  ;;
*)
  archivedir=/mnt/storage/archive
  ;;
esac

proposalidentifiers_csv=/mnt/storage/local/etc/proposalidentifiers.csv

mkdir -p $archivedir/public/
cd $archivedir/public/

export LC_CTYPE=en_US.UTF-8

cp $proposalidentifiers_csv proposalidentifiers.csv-$$-tmp

awk -F, '
{
  printf("%s %5s %-30s %s\n", $1, $2, $3, $4);
}
' proposalidentifiers.csv-$$-tmp >proposalidentifiers.txt-$$-tmp

install -CpS  proposalidentifiers.csv-$$-tmp proposalidentifiers.csv
install -CpS  proposalidentifiers.txt-$$-tmp proposalidentifiers.txt

rm -f proposalidentifiers.*-tmp
