#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2016, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

#\
umask 0; exec /usr/bin/tclsh8.6 -encoding "utf-8" "$0" ${1+"$@"}


########################################################################

proc checktemperature {filename criticalmin warningmin warningmax criticalmax} {

  set channel [open $filename "r"]
  set line [gets $channel]
  close $channel

  if {[scan $line "%f" temperature] != 1} {
    return [list 1 "unknown"]
  }

  set temperature [format "%.1f" $temperature]

  if {$temperature < $criticalmin || $temperature > $criticalmax} {
    return [list 2 "$temperature C"]
  } elseif {$temperature < $warningmin || $temperature > $warningmax} {
    return [list 1 "$temperature C"]
  } else {
    return [list 0 "$temperature C"]
  }
}

########################################################################

set result  [checktemperature /var/ow/28.4720E1020000/temperature 5.0 10.0 25.0 30.0]
set status  [lindex $result 0]
set message [lindex $result 1]

switch $status {
  0 {
    set statustext "OK"
  }
  1 {
    set statustext "WARNING"
  }
  2 {
    set statustext "CRITICAL"
  }
}

puts "COMPRESSOR SUPPLY TEMPERATURE $statustext - $message."
exit $status
