#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

# $Id: checkreboot 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

# Try to work even if $tcsprefix is read-only.
if test ! -w "$tcsprefix"
then
  tcsprefix=/run
fi

mkdir -p "$tcsprefix"/var/tcs/reboot
cd "$tcsprefix"/var/tcs/reboot

# Get the unqualified host name and remove any prefix before "-".
host="$(uname -n | sed 's/\..*//;s/[^-]*-//')"

# The sleep below aim to ensure that the log server stops after the
# other servers have stopped.

if test -f "$host"
then
  # We are on the main host, which runs the log server.
  sleep 10
  tcs log "tcs checkreboot" summary "rebooting $host."
  rm -f "$host"
  sleep 1
  shutdown -r now
else
  # We are not on the main host.
  rsync -a --timeout=10 --include="$host" --exclude="*" --remove-source-files rsync://services/tcs/reboot/. .
  if test -f "$host"
  then
    tcs log "tcs checkreboot" summary "rebooting $host."
    rm -f "$host"
    sleep 1
    shutdown -r now
  fi
fi

exit 0
