#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

# $Id: checkrestart 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

mkdir -p "$tcsprefix"/var/tcs/restart
cd "$tcsprefix"/var/tcs/restart

# Get the unqualified host name and remove any prefix before "-".
host="$(uname -n | sed 's/\..*//;s/[^-]*-//')"

if test -f "$host"
then
  rm -f "$host"
  sleep 10
  tcs stopserver -a
  tcs startserver -a
else
  # We are not on the main host.
  rsync -a --timeout=10 --include="$host" --exclude="*" --remove-source-files rsync://services/tcs/restart/. .
  if test -f "$host"
  then
    rm -f "$host"
    tcs stopserver -a
    sleep 30
    tcs startserver -a
  fi
fi

exit 0
