#!/bin/sh

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program url"
  exit 1
}

error () {
  echo 1>&2 "$(date -u '+%F %T'): $program: error: $@"
  exit 1
}

log () {
  echo 1>&2 "$(date -u '+%F %T'): $program: $@"
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1
then
  usageerror
fi

url="$1"

log "starting."

################################################################################

etcdir="$tcsprefix"/etc/tcs/

cd "$etcdir"

################################################################################

log "cloning to blocks.new/."
rm -rf blocks.new
mkdir blocks.new
if ! git clone -q $url blocks.new/
then
  error "clone failed."
fi

################################################################################

log "moving blocks/ to blocks.old/."
rm -rf blocks.old
mv blocks blocks.old

################################################################################

log "moving blocks.new/ to blocks/."
mv blocks.new blocks

################################################################################

log "finished."

exit 0

################################################################################
