#!/bin/sh

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program url"
  exit 1
}

error () {
  log error "$@"
  exit 1
}

log () {
  level=$1
  shift
  tcs log "$program" $level "$*"
  echo 1>&2 "$(date -u '+%F %T'): $program: $level: $*"
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# = 0
then
  case $(hostname) in
  coatlioan-*)
    url="https://github.com/alanwatsonforster/coatlioan-blocks.git"
    ;;
  ddotioan-*)
    url="https://github.com/alanwatsonforster/ddotioan-blocks.git"
    ;;
  *)
    error "unable to determing URL."
    ;;
  esac
elif test $# = 1
then
  url="$1"
else
  usageerror
fi

log summary "fetching blocks."

################################################################################

etcdir="$tcsprefix"/etc/tcs/

cd "$etcdir"

################################################################################

log info "cloning from $url to blocks.new/."
rm -rf blocks.new
mkdir blocks.new
if ! git clone -q $url blocks.new/
then
  error "clone failed."
fi

################################################################################

log info "moving blocks/ to blocks.old/."
rm -rf blocks.old
mv blocks blocks.old

################################################################################

log info "moving blocks.new/ to blocks/."
mv blocks.new blocks

################################################################################

log summary "finished fetching blocks."

exit 0

################################################################################
