#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-l] [--] [fitsfile ...]"
  exit 1
}

optstring="l"
list=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -l)
    list=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
case "$#" in
0)
  set -- "/dev/stdin"
  ;;
*)
  ;;
esac

for fitsfile in "$@"
do

  datasection="$(tcs fitsheadervalue DATASEC "$fitsfile")"
  if test -z "$datasection"
  then
    naxis1="$(tcs fitsheadervalue NAXIS1 "$fitsfile")"
    naxis2="$(tcs fitsheadervalue NAXIS2 "$fitsfile")"
    datasection="[1:$naxis1,1:$naxis2]"
  fi

  IFS=" " set -- $(echo "$datasection" | sed 's/[^0-9]/ /g')
  xmin=$1
  xmax=$2
  ymin=$3
  ymax=$4

  sx=$(expr $xmin - 1)
  sy=$(expr $ymin - 1)
  nx=$(expr $xmax - $xmin + 1)
  ny=$(expr $ymax - $ymin + 1)
  
  if $list
  then
    echo $sx $sy $nx $ny $fitsfile
  else 
    echo $sx $sy $nx $ny
  fi

done

exit 0
