#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: fitsfwhm 3550 2020-05-22 17:22:28Z Alan $

########################################################################

# Copyright © 2013, 2015, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program=$(basename "$0")

usageerror () {
  echo 1>&2 "usage: $program [-e etcdir] [-s section] [-S saturationlevel] [-m] [-A] [-w wisdom] [--] fitsfile"
  exit 1
}

optstring=e:s:S:mAw:
etcdir=/usr/local/etc/tcs
saturationlevel="DATASAT"
section="DATASEC"
median=0
autocorrelation=false
wisdom=/usr/local/var/tcs/wisdom
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -e)
    etcdir="$2"
    shift 2
    ;;
  -s)
    section="$2"
    shift 2
    ;;
  -S)
    saturationlevel="$2"
    shift 2
    ;;
  -m)
    median=1
    shift 1
    ;;
  -A)
    autocorrelation=true
    shift
    ;;
  -w)
    wisdom="$2"
    shift 2
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1
then
  usageerror
fi

fitsfile="$1"

if test "$section" = "DATASEC"
then
  section="$(fitsheadervalue DATASEC "$fitsfile")"
fi
if test -z "$section" || test "$section" = "none"
then
  naxis1=$(fitsheadervalue NAXIS1 "$fitsfile")
  naxis2=$(fitsheadervalue NAXIS2 "$fitsfile")
  section="[1:$naxis1,1:$naxis2]"
fi
set -- $(echo "$section" | sed 's/[^0-9]/ /g')
xmin=$1
xmax=$2
ymin=$3
ymax=$4

if test "$saturationlevel" = "DATASAT"
then
  saturationlevel="$(expr $(fitsheadervalue DATASAT "$fitsfile") / 2)"
fi

if $autocorrelation
then
  wsx=$(expr $xmin - 1)
  wsy=$(expr $ymin - 1)
  wnx=$(expr $xmax - $xmin + 1)
  wny=$(expr $ymax - $ymin + 1)
  fitpsf "$fitsfile" $wsx $wnx $wsy $wny 16 3 "$wisdom" 2>/dev/null
else
  if test ! -z "$saturationlevel" && test "$saturationlevel" != "none"
  then
    saturationlevelflags="-SATUR_LEVEL $saturationlevel"
  fi
  sextractor "$fitsfile" \
    -c "$etcdir"/fitsfwhm.sex \
    -PARAMETERS_NAME "$etcdir"/fitsfwhm.param \
    $saturationlevelflags \
    -CATALOG_NAME STDOUT 2>&- |
  sort -k 4n |
  awk -v xmin=$xmin -v xmax=$xmax -v ymin=$ymin -v ymax=$ymax '
  {
    x = $1;
    y = $2;
    if (xmin <= x && x <= xmax && ymin <= y && y <= ymax) {
      print $0;
    }
  }
  ' |
  awk -v median=$median '
  BEGIN {
    ibrightest = "";
    i = 0;
  }
  {
    flags = $5;
    if (flags < 2) {
      x[i]    = $1;
      y[i]    = $2;
      fwhm[i] = $3;
      mag[i]  = $4;
      if (ibrightest == "" || mag[i] <= mag[ibrightest]) {
        ibrightest = i;
      }
      ++i;
    }
  }
  END {
    if (!median) {
      iselected = ibrightest
    } else if (i > 0) {
      iselected = int(i / 2);
    } else {
      iselected = "";
    }
    if (iselected != "") {
      printf "%6.2f %6.2f %6.2f\n", fwhm[iselected], x[iselected], y[iselected];
    }
  }
  '
fi

exit 0
