#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: gcntantest 3575 2020-05-23 19:47:32Z Alan $

########################################################################

# Copyright © 2012, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

#\
umask 0; PATH=/usr/local/opt/tcl-tk/bin:$PATH exec tclsh8.6 -encoding "utf-8" "$0" ${1+"$@"}

set env("logtostderronly") "true"

source [file join $::env(tcsprefix) "lib" "tcs" "packages.tcl"]

package provide "selectorclient" 0.0
namespace eval "selectorclient" {

  proc request {request} {
    puts "selector: request: $request"
  }

}

package provide "server" 0.0
namespace eval "server" {

  proc setdata {key value} {
  }

}

package require "gcntan"

namespace eval "gcntan" {

  while {[gets stdin line] > 0} {
    puts $line
    if {[llength $line] != 46} {
      log::error "invalid line."
    } else {
      set timestamp "[lindex $line 0] [lindex $line 1]"
      set packet [lrange $line 6 end]
      gcntan::processpacket $timestamp $packet
    }
  }

}