#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

set -x

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program name [on|off]"
  exit 1
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1 && test $# != 2
then
  usageerror
fi

host=$(uname -n | tr A-Z a-z | sed 's/\..*//')

name="$1"
value="$2"
case $name:$host in
19:*|26:*|472:*|473:*|475:*|476:*|480:*|481:*|482:*|483:*)
  gpio=$name
  ;;
enclosure-lights:quetzalcoatl-platform|enclosure-lights:ddoti-platform)
  gpio=19
  ;;
enclosure-heater:quetzalcoatl-platform|enclosure-heater:ddoti-platform)
  gpio=26
  ;;
enclosure-lights:quetzalcoatl-c0|enclosure-lights:ddoti-c0|telescope-fans:ddoti-d0|telescope-fans:ddoti-e0)
  gpio=481
  ;;
enclosure-heater:quetzalcoatl-c0|enclosure-heater:ddoti-c0)
  gpio=476
  ;;
*)
  echo 1>&2 "error: invalid name \"$name\"."
  exit 1
  ;;
esac

if test $# = 1
then
  if test $(gpioget gpiochip0 $gpio) = 0
  then
    echo "off"
  else
    echo "on"
  fi
else
  if test "$value" = "off"
  then
    gpioset gpiochip0 $gpio=0
  elif test "$value" = "on"
  then
    gpioset gpiochip0 $gpio=1
  else
    echo 1>&2 "$program: invalid value \"$value\"."
    exit 1
  fi
fi

exit 0
