#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: instrumentdataserver 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

trap '' HUP

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-f] [-j] [-z] [-d] [--] destination"
  exit 1
}

optstring=fjzd
compress="bzip2 -1kf"
rsync="rsync"
suffix="bz2"
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -z)
    compress="gzip -1f"
    suffix="gz"
    shift
    ;;
  -j)
    compress="bzip2 -1f"
    suffix="bz2"
    shift
    ;;
  -f)
    compress="fpack -D"
    suffix="fz"
    shift
    ;;
  -d)
    rsync="rsync --remove-source-files"
    shift
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1
then
  usageerror
fi
dst="$1"

cd "$tcsprefix"/var/tcs
while true
do
  (
    find . -name "*C[0-9]?.fits"
    find . -name "*C[0-9]?c.fits"
  ) | 
  while read fits
  do
    tcs fitsheader $fits >$fits.txt
    $compress $fits
    $rsync -aR $fits.txt $fits.$suffix "$dst"
  done
  (
    find . -name "*C[0-9]?.fits.txt"
    find . -name "*C[0-9]?.fits.$suffix"
  ) | while read file
  do
    $rsync -aR $file "$dst"
  done
  rsync -l latest "$dst"
  sleep 5
done
