#!/bin/sh

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-d seconds] [--] command"
  exit 1
}

optstring=d:
delay=0
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -d)
    delay="$2"
    shift 2
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1
then
  usageerror
fi

while true
do
    sh -c "$1"
    sleep $delay
done
