#!/bin/sh

#!/bin/sh

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program"
  exit 1
}

error () {
  log error "$@"
  exit 1
}

log () {
  level=$1
  shift
  tcs log "$program" $level "$*"
  echo 1>&2 "$(date -u '+%F %T'): $program: $level: $*"
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

################################################################################

sudo mkdir -p /usr/local/var/www/tcs/blocks
sudo rsync --delete -ah /usr/local/var/tcs/blocks/ /usr/local/var/www/tcs/blocks/

exit 0

################################################################################
