#!/usr/bin/env python3

import os
from datetime import datetime
from datetime import timezone
import json
import re
import math

htmlfilename = "/usr/local/var/www/tcs/alerts.html"
jsonfilename = "/usr/local/var/tcs/alerts.json"

htmlfile = open(htmlfilename, "w")


def readjson(filename):
    with open(filename, "r") as f:
        return json.loads(f.read(-1))


def writehtml(s):
    print(s, file=htmlfile)


def formattimestamp(timestamp):
    timestamp = re.sub("T", " ", timestamp)
    timestamp = re.sub("\.[0-9]*$", "", timestamp)
    return timestamp


def formatage(age):
    return "%.2fd" % (age / 86400)


def parseangle(angle):
    if angle[-1:] == "r":
        angle = float(angle[:-1])
    elif angle[-1:] == "d":
        angle = math.radians(float(angle[:-1]))
    elif angle[-2:] == "am":
        angle = math.radians(float(angle[:-2]) / 60)
    elif angle[-2:] == "as":
        angle = math.radians(float(angle[:-2]) / 60 / 60)
    else:
        angle = float(angle)
    return angle


def parseinterval(interval):
    if interval[-1:] == "d":
        interval = float(interval[:-1]) * 60 * 60 * 24
    elif interval[-1:] == "h":
        interval = float(interval[:-1]) * 60 * 60
    elif interval[-1:] == "m":
        interval = float(interval[:-1]) * 60
    elif interval[-1:] == "s":
        interval = float(interval[:-1])
    else:
        interval = float(interval)
    return interval


def age(timestamp):
    timestamp = re.sub("\.[0-9]*$", "", timestamp)
    event = datetime.fromisoformat(timestamp)
    now = datetime.now()
    age = now - event
    return age.days * 86400 + age.seconds


alerts = readjson(jsonfilename)

writehtml(
    """
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" href="style.css" type="text/css"/>
<title>Alerts</title>
</head>

<body>

<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="config.js"></script>
<script type="text/javascript" src="alerts.js"></script>

<div id="title">
<h1>Alerts</h1>
<hr/>
</div>

<div id="body">
"""
)

writehtml(
    """

<p>
<a href="/index.html">Home</a> |
<a href="https://github.com/unam-transients/tcs/wiki/Creating-and-Modifying-Alerts-Manually">Help</a>
</p>

<hr/>

<table class="alertsinputs">
<tr class="alertsinputs">
<td class="alertsinputs"><form id="alert-refresh"><input type="submit" value="Refresh"/></form></td>
<td class="alertsinputs"><form id="alert-rugby"><input type="submit" value="Rugby"/></form></td>
</tr>
</table>

<hr/>

<table class="alertsinputs">
<tr class="alertsinputs">
<td class="alertsinputs"><form id="alert-enable"><input type="submit" value="Enable"/></form></td>
<td class="alertsinputs"><form id="alert-disable"><input type="submit" value="Disable"/></form></td>
</tr>
</table>

<hr/>

<table class="alertsinputs">
<tr class="alertsinputs">
<td class="alertsinputs"><form id="alert-modify"><input type="submit" value="Modify"/></form></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">α</td>
<td class="alertsinputs"><input type="text" id="modify-alpha" name="modify-alpha"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">δ</td>
<td class="alertsinputs"><input type="text" id="modify-delta" name="modify-delta"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Uncertainty</td>
<td class="alertsinputs"><input type="text" id="modify-uncertainty" name="modify-uncertainty"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Max Age</td>
<td class="alertsinputs"><input type="text" id="modify-max-age" name="modify-max-age"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Priority</td>
<td class="alertsinputs"><input type="text" id="modify-priority" name="modify-priority"></td>
</tr>
</table>

<hr/>

<table class="alertsinputs">
<tr class="alertsinputs">
<td class="alertsinputs"><form id="alert-create"><input type="submit" value="Create"/></form></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Name</td>
<td class="alertsinputs"><input type="text" id="create-name" name="create-name"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Event Time</td>
<td class="alertsinputs"><input type="text" id="create-eventtime" name="create-eventtime"></td>
</tr>
<tr>
<td class="alertsinputs">α</td>
<td class="alertsinputs"><input type="text" id="create-alpha" name="create-alpha"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">δ</td>
<td class="alertsinputs"><input type="text" id="create-delta" name="create-delta"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Uncertainty</td>
<td class="alertsinputs"><input type="text" id="create-uncertainty" name="create-uncertainty"></td>
</tr>
<tr class="alertsinputs">
<td class="alertsinputs">Priority</td>
<td class="alertsinputs"><input type="text" id="create-priority" name="create-priority"></td>
</tr>
</table>


<hr/>
""")

alerts.sort(key=lambda x: x["eventtimestamp"], reverse=True)

selectablealerts = []
unselectablealerts = []
for alert in alerts:
    if "uncertainty" not in alert.keys() or "eventtimestamp" not in alert.keys() or "enabled" not in alert.keys():
        unselectablealerts.append(alert)
    elif alert["enabled"] == "false":
        unselectablealerts.append(alert)
    elif parseangle(alert["uncertainty"]) > parseangle(alert["maxalertuncertainty"]):
        unselectablealerts.append(alert)
    elif age(alert["eventtimestamp"]) > parseinterval(alert["maxalertdelay"]):
        unselectablealerts.append(alert)
    else:
        selectablealerts.append(alert)


def writealertstable(alerts, name):
    if len(alerts) == 0:
        writehtml('<tr><th colspan="15">No %s</th></tr>' % name)
        writehtml('<tr><td colspan="15"><hr/></td></tr>')
        return
    else:
        writehtml('<tr><th colspan="15">%s</th></tr>' % name)
        writehtml('<tr><td colspan="15"><hr/></td></tr>')
        writehtml("<tr>")
        for text in [
            "Name",
            "Event Time",
            "Age",
            "Max Age",
            "α",
            "δ",
            "Epoch",
            "Uncertainty",
            "Priority",
            "Enabled",
            "Identifier",
            "SVOM Identifier",
            "Swift Identifier",
            "Fermi Identifier",
            "LVC Identifier",
        ]:
            writehtml('<th class="alertstable">%s</th>' % text)
        writehtml("</tr>")
        for alert in alerts:
            writehtml("<tr>")
            for key in [
                "name",
                "eventtimestamp",
                "age",
                "maxage",
                "alpha",
                "delta",
                "equinox",
                "uncertainty",
                "priority",
                "enabled",
                "identifier",
                "svomidentifier",
                "swiftidentifier",
                "fermiidentifier",
                "lvcidentifier",
            ]:
                writehtml('<td class="alertstable">')
                if key == "age" and "eventtimestamp" in alert.keys():
                    writehtml(formatage(age(alert["eventtimestamp"])))
                elif key == "maxage" and "maxalertdelay" in alert.keys():
                    writehtml(formatage(parseinterval(alert["maxalertdelay"])))
                elif key not in alert.keys():
                    writehtml("—")
                elif key == "identifier":
                    writehtml('<a href="alerts/%s">%s</a>' % (alert["identifier"], alert["identifier"]))
                elif key == "name":
                    writehtml('<input type="radio" name="identifier" id="%s" value="%s" class="alertstable"><label for="%s">%s</label>' % (alert["identifier"], alert["identifier"], alert["identifier"], alert[key]))
                elif key == "eventtimestamp":
                    writehtml(formattimestamp(alert[key]))
                elif alert[key] != "" and alert[key][0] == "-":
                    writehtml("&minus;%s" % alert[key][1:])
                else:
                    writehtml(alert[key])
                writehtml("</td>")
            writehtml("</tr>")


writehtml('<table class="alertstable">')
writealertstable(selectablealerts, "Selectable Alerts")
writehtml('<tr><td colspan="15"><hr/></td></tr>')
writealertstable(unselectablealerts, "Unselectable Alerts")
writehtml("</table>")

writehtml(
    """
</div>

<div>
<hr/>
Updated: %s UTC
</div>

</body>


</html>
"""
    % datetime.now(timezone.utc).replace(tzinfo=None).isoformat(" ", timespec="seconds")
)
