#!/usr/bin/env python3

import glob
from datetime import datetime
from datetime import timezone
import platform
import re
import sys
import os
import json

prefix = "/usr/local/var/"

args = sys.argv[1:]
if len(args) == 0:
    args = ["latest"]


def writehtmlfile(date, observationsdict):

    htmlfilename = "%s/www/tcs/observations/%s.html" % (prefix, date)

    htmldirname = os.path.dirname(htmlfilename)
    if not os.path.exists(htmldirname):
        os.makedirs(htmldirname)

    if platform.node().startswith("coatli"):
        project = "coatli"
        projectname = "COATLI"
    elif platform.node().startswith("colibri"):
        project = "colibri"
        projectname = "COLIBRÍ"
    elif platform.node().startswith("ddoti"):
        project = "ddoti"
        projectname = "DDOTI"
    else:
        raise RuntimeError("unknown project.")

    with open(htmlfilename, "w") as sys.stdout:

        if date == "latest":
            title = "%s: Latest Observations" % projectname
        else:
            title = "%s: Observations for %s" % (projectname, date)

        print(
            """
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

        <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="stylesheet" href="../style.css" type="text/css"/>
        <title>%s</title>
        </head>

        <body>

        <div id="title">
        <h1>%s</h1>
        <hr/>
        </div>

        <div id="body">
        """
            % (title, title)
        )

        print('<table class="observationstable">')
        print("<tr>")
        print("<th></th>")
        print("<th></th>")
        print(
            '<th class="observationstable" colspan="13" style="text-align:center">Exposure Time (s)</th>'
        )
        print("</tr>")

        print("<tr>")
        for text in [
            "Program",
            "Block",
            "Total",
            "C0",
            "C1",
            "C2",
            "C3",
            "B",
            "g",
            "r",
            "i",
            "gri",
            "z",
            "y",
            "zy",
            "Start",
            "End",
            "Block Name",
        ]:
            print('<th class="observationstable">%s</th>' % text)
        print("</tr>")

        for key in sorted(observationsdict.keys()):

            print("<tr>")
            print(
                '<td class="observationstable">%s</td>'
                % observationsdict[key]["proposalidentifier"]
            )
            print(
                '<td class="observationstable">%s</td>'
                % observationsdict[key]["blockidentifier"]
            )
            for exposuresuffix in [
                "",
                "C0",
                "C1",
                "C2",
                "C3",
                "B",
                "g",
                "r",
                "i",
                "gri",
                "z",
                "y",
                "zy",
            ]:
                print(
                    '<td class="observationstable">%.0f</td>'
                    % observationsdict[key]["exposuretime" + exposuresuffix]
                )
            print(
                '<td class="observationstable">%s</td>'
                % observationsdict[key]["startdate"]
            )
            print(
                '<td class="observationstable">%s</td>'
                % observationsdict[key]["enddate"]
            )
            print(
                '<td class="observationstable">%s</td>'
                % observationsdict[key]["blockname"]
            )
            print("</tr>")

        totalexposurettime = {}
        for exposuresuffix in [
            "",
            "C0",
            "C1",
            "C2",
            "C3",
            "B",
            "g",
            "r",
            "i",
            "gri",
            "z",
            "y",
            "zy",
        ]:
            totalexposurettime[exposuresuffix] = 0
        for key in sorted(observationsdict.keys()):
            for exposuresuffix in [
                "",
                "C0",
                "C1",
                "C2",
                "C3",
                "B",
                "g",
                "r",
                "i",
                "gri",
                "z",
                "y",
                "zy",
            ]:
                totalexposurettime[exposuresuffix] += observationsdict[key][
                    "exposuretime" + exposuresuffix
                ]
        print("<tr>")
        print('<td class="observationstable" colspan="2">Total</td>')
        for exposuresuffix in [
            "",
            "C0",
            "C1",
            "C2",
            "C3",
            "B",
            "g",
            "r",
            "i",
            "gri",
            "z",
            "y",
            "zy",
        ]:
            print(
                '<td class="observationstable">%.0f</td>'
                % totalexposurettime[exposuresuffix]
            )
        print("</tr>")

        print(
            """
        </table>
        """
        )

        print(
            """
        <hr/>
        <p>Updated: %s UTC</p>
        </div>

        </body>


        </html>
        """
            % datetime.now(timezone.utc)
            .replace(tzinfo=None)
            .isoformat(" ", timespec="seconds")
        )


def writejsonfile(date, observationsdict):

    jsonfilename = "%s/www/tcs/observations/%s.json" % (prefix, date)

    jsondirname = os.path.dirname(jsonfilename)
    if not os.path.exists(jsondirname):
        os.makedirs(jsondirname)
    
    with open(jsonfilename, "w") as jsonfile:
        json.dump(observationsdict, jsonfile, indent=4)


for date in args:

    observationsdict = {}

    for path in glob.glob("%s/tcs/%s/executor/images/*/*/*/*fits.txt" % (prefix, date)):
        try:
            with open(path) as f:
                s = f.read()

                m = re.search(r"^PRPID *= *0*([0-9]+)", s, flags=re.MULTILINE)
                proposalidentifier = int(m.group(1)) if m is not None else 0
                proposalidentifier = "%04d" % proposalidentifier

                m = re.search(r"^BLKID *= *0*([0-9]+)", s, flags=re.MULTILINE)
                blockidentifier = int(m.group(1)) if m is not None else 0
                blockidentifier = "%04d" % blockidentifier

                m = re.search(r"^BLKNM *= *'([^']*)", s, flags=re.MULTILINE)
                blockname = m.group(1) if m is not None else ""

                m = re.search(r"^FILTER *= *'([^']*)", s, flags=re.MULTILINE)
                filter = m.group(1) if m is not None else ""

                m = re.search(r"^CCD_NAME *= *'([^']*)", s, flags=re.MULTILINE)
                detector = m.group(1) if m is not None else ""

                m = re.search(r"^EXPTIME *= *([0-9.]+)", s, flags=re.MULTILINE)
                exposuretime = float(m.group(1)) if m is not None else ""

                m = re.search(r"^SDATE *= *'([^']*)", s, flags=re.MULTILINE)
                startdate = m.group(1)[11:19] if m is not None else ""

                m = re.search(r"^EDATE *= *'([^']*)", s, flags=re.MULTILINE)
                enddate = m.group(1)[11:19] if m is not None else ""

                key = "%s/%s" % (proposalidentifier, blockidentifier)

                if key not in observationsdict:
                    observationsdict[key] = {
                        "proposalidentifier": proposalidentifier,
                        "blockidentifier": blockidentifier,
                        "blockname": blockname,
                        "exposuretime": 0,
                        "exposuretimeB": 0,
                        "exposuretimeg": 0,
                        "exposuretimer": 0,
                        "exposuretimei": 0,
                        "exposuretimegri": 0,
                        "exposuretimez": 0,
                        "exposuretimey": 0,
                        "exposuretimezy": 0,
                        "exposuretimeC0": 0,
                        "exposuretimeC1": 0,
                        "exposuretimeC2": 0,
                        "exposuretimeC3": 0,
                        "startdate": startdate,
                        "enddate": enddate,
                    }
                observationsdict[key]["exposuretime"] += exposuretime
                if filter != "":
                    observationsdict[key]["exposuretime" + filter] += exposuretime
                if detector != "":
                    observationsdict[key]["exposuretime" + detector] += exposuretime
                if startdate != "" and startdate < observationsdict[key]["startdate"]:
                    observationsdict[key]["startdate"] = startdate
                if enddate != "" and enddate > observationsdict[key]["enddate"]:
                    observationsdict[key]["enddate"] = enddate
        except:
            pass

    writehtmlfile(date, observationsdict)
    writejsonfile(date, observationsdict)
