#!/bin/sh

########################################################################

# This file is part of the RATTEL telescope control system.

########################################################################

# Copyright © 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

sudo -v

program="tcs $(basename "$0")"

export TCSLOGTOSTDERR=true

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case $host in
*-control)
  ;;
*)
  echo 1>&2 "$program: error: must run on the control host." 
  exit 1
  ;;
esac

if test $# = 0
then
  case "$host" in
  coatli-control)
    instrument=huitzi
    ;;
  ddoti-control)
    instrument=ddoti
    ;;
  colibri-control)
    instrument=tequila
    ;;
  *)
    echo 2>&1 "$program: error: unknown host."
    exit 1
    ;;
  esac
elif test $# = 1
then
  instrument="$1"
else
  echo 2>&1 "usage: $program [instrument]"
  exit 1
fi

case "$instrument" in
  huitzi)
    hosts=instrument
    powers=instrument
    ;;
  ddoti)
    hosts="detectors0 detectors1"
    powers="instrument"
    ;;
  tequila)
    hosts="tequila"
    powers="tequila"
    ;;
  *)
    echo 2>&1 "$program: error: unknown instrument \"$instrument\"."
    exit 1
    ;;
esac

tcs log "tcs rebootinstrument" summary "rebooting $instrument."

for host in "$hosts"
do
  tcs log "tcs rebootinstrument" summary "requesting $host to halt."
  sudo tcs halt $host
done

for host in $hosts
do
  tcs log "tcs rebootinstrument" summary "waiting for $host to halt."
  while ping -c 1 -W 1 $host >/dev/null 2>&1
  do
    sleep 1
  done
done
sudo rm -f /usr/local/var/tcs/halt/*

for power in $powers
do
  tcs log "tcs rebootinstrument" summary "switching off $power."
  tcs request power switchoff $power
done

# We wait for 2 minutes to give the capacitors a chance to discharge.
tcs log "tcs rebootinstrument" summary "waiting for 2 minutes."
sleep 120

for power in $powers
do
  tcs log "tcs rebootinstrument" summary "switching on $power."
  tcs request power switchon $power
done

for host in $hosts
do
  tcs log "tcs rebootinstrument" summary "waiting for $host to reboot."
  while ! ping -c 1 -W 1 $host >/dev/null 2>&1
  do
    sleep 1
  done
done

for host in $hosts
do
  tcs log "tcs rebootinstrument" summary "tcs will now boot on $host."
done

tcs log "tcs rebootinstrument" summary "finished rebooting $instrument."

exit 0
