#!/bin/sh

########################################################################

# This file is part of the RATTEL telescope control system.

########################################################################

# Copyright © 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export TCSLOGTOSTDERR=true

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case $host in
*-services)
  ;;
*)
  echo 1>&2 "$program: error: must run on the services host." 
  exit 1
  ;;
esac

if test $# = 0
then
  case "$host" in
  coatlioan-services)
    set instrument
    ;;
  ddotioan-services)
    set instrument0 instrument1
    ;;
  *)
    echo 2>&1 "$program: error: unknown host."
    exit 1
    ;;
  esac
fi

sudo -v

tcs log "tcs rebootinstrument" summary "rebooting instrument."

for host in "$@"
do
  tcs log "tcs rebootinstrument" info "requesting $host to halt."
  sudo tcs haltsoon $host
done

for host in "$@"
do
  tcs log "tcs rebootinstrument" info "waiting for $host to halt."
  while ping -c 1 -W 1 $host >/dev/null 2>&1
  do
    sleep 1
  done
done
sudo rm -f /usr/local/var/tcs/halt/*

tcs log "tcs rebootinstrument" info "switching off instrument."
tcs request power switchoff instrument

# We wait for 2 minutes to give the capacitors a chance to discharge.
tcs log "tcs rebootinstrument" info "waiting for 2 minutes."
sleep 120

tcs log "tcs rebootinstrument" info "switching on instrument."
tcs request power switchon instrument

for host in "$@"
do
  tcs log "tcs rebootinstrument" info "waiting for $host to reboot."
  while ! ping -c 1 -W 1 $host >/dev/null 2>&1
  do
    sleep 1
  done
done

tcs log "tcs rebootinstrument" summary "finished rebooting instrument."
for host in "$@"
do
  tcs log rebootplatform summary "tcs will now boot on $host."
done

exit 0
