#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2010, 2011, 2012, 2013, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

libexecdir="$tcsprefix/libexec/tcs"
program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-d] [--] servername [...]"
  echo 1>&2 "usage: $program [-d] [-f] [--] servername"
  echo 1>&2 "usage: $program [-d] [-a] [--]"
  echo 1>&2 "usage: $program [-d] [-A] [--]"
  exit 1
}

optstring=aAdf
all=false
ALL=false
debug=false
foreground=false
startopts=""
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  -A)
    ALL=true
    shift 1
    ;;
  -d)
    debug=true
    startopts="$startopts -d"
    shift 1
    ;;
  -f)
    foreground=true
    startopts="$startopts -f"
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift

if $all && $ALL
then
  usageerror
elif ($all || $ALL) && $foreground
then
  usageerror
elif ($all || $ALL) && test $# != 0
then
  usageerror
elif ! ($all || $ALL) && test $# = 0
then
  usageerror
elif $foreground && test $# != 1
then
  usageerror
fi

if $all
then
  "$libexecdir"/stopserver -a
  "$libexecdir"/startserver $startopts -a
elif $ALL
then
  "$libexecdir"/stopserver -A
  "$libexecdir"/startserver $startopts -A
else
  "$libexecdir"/stopserver -- "$@"
  "$libexecdir"/startserver $startopts -- "$@"
fi

exit 0
