#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

sudo -v

program="tcs $(basename "$0")"

export TCSLOGTOSTDERR=true

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case $host in
*-services)
  ;;
*)
  echo 1>&2 "$program: error: must run on the services host." 
  exit 1
  ;;
esac

sudo mkdir -p "$tcsprefix"/var/tcs/restart
cd "$tcsprefix"/var/tcs/restart

if test $# = 0
then
  case "$host" in
  coatlicu-*)
    set control instrument
    ;;
  oan-coatli-*)
    set services control platform instrument
    ;;
  ddotioan-*)
    set services control platform instrument0 instrument1
    ;;
  colibriohp-*)
    set services detectors
    ;;
  *)
    echo 2>&1 "$program: error: unknown host."
    exit 1
    ;;
  esac
fi

for host in "$@"
do
  if ping -c 1 -W 1 $host >/dev/null 2>&1
  then
    tcs log "tcs restart" summary "requesting restart of tcs on $host."
    sudo touch "$host"
  else
    tcs log "tcs restart" warning "not requesting restart of tcs of $host as it appears to be down."
  fi
done

tcs log "tcs restart" summary "restarts of tcs will occur shortly."

exit 0
