#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: secondaryserver-project-ratiroan 3608 2020-06-11 18:34:27Z Alan $

########################################################################

# Copyright © 2009, 2010, 2011, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

#\
umask 0; PATH=/usr/local/opt/tcl-tk/bin:$PATH exec tclsh8.6 -encoding "utf-8" "$0" ${1+"$@"}

source [file join $::env(tcsprefix) "lib" "tcs" "packages.tcl"]

package require "config"

# The actual range is more like 0 to 19150, but we want to stay away
# from the limits.

config::setdefaultvalue "secondary" "controllerhost"    "secondary-z"
config::setdefaultvalue "secondary" "controllerport"    3333
config::setdefaultvalue "secondary" "minz"              500
config::setdefaultvalue "secondary" "maxz"              18500
config::setdefaultvalue "secondary" "initialz0"  6500
config::setdefaultvalue "secondary" "dztweak"           +30
config::setdefaultvalue "secondary" "dzdzenithdistance" +352.0
config::setdefaultvalue "secondary" "dzdha"               -6.5
config::setdefaultvalue "secondary" "dzddelta"           -14.0
config::setdefaultvalue "secondary" "dzdT"                35.0
config::setdefaultvalue "secondary" "temperaturesensor" "dome-temperature"
config::setdefaultvalue "secondary" "allowedzerror"     1
config::setdefaultvalue "secondary" "zdeadzonewidth"    5

package require "server"
server::start {
  config::setdefaultvalue "secondary" "type" ratir
  package require secondaryserver
  secondaryserver::start
}
