#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2024 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program category message"
  exit 1
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 2
then
  usageerror
fi
category="$1"
message="$2"

case $(uname -n) in
coatli-*)
  source="COATLI"
  ;;
ddoti-*)
  source="DDOTI"
  ;;
colibri-*)
  source="COLIBRI"
  url="https://mattermost.osupytheas.fr/hooks/8d36q11tzp8e7yxdnc7czhosdw"
  ;;
*)
  echo 2>&1 "$program: error: chat is not configured for $(uname -n)."
  exit 1
  ;;
esac

test="https://chat.googleapis.com/v1/spaces/AAAAvPDdHcE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=aj0Xc4tJMEI32XNmBcD70mZ0KzyziQNjLqH458UfgMU"
coatlioan="https://chat.googleapis.com/v1/spaces/AAAAIjRMy3k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=KmgPQ0Ccob9q92uy5RKm64F90EG4uk2vHKZ4DDLWh28"
ddotioan=$coatlioan
colibrioan="https://chat.googleapis.com/v1/spaces/AAAA0_-MXYw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=B6AEIpKYVfJzXdYDzkGzLciMi_DKzvzY0rk_2ySCaqg"
colibrilam="https://mattermost.osupytheas.fr/hooks/8d36q11tzp8e7yxdnc7czhosdw"
alerts="https://chat.googleapis.com/v1/spaces/AAAAUwc_GEQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Ib_4l1JFkAlA92xd-0mOf-AyOpZZ37dBHLz3kPLSzAI"

case $(uname -n):$category in
coatli-*:operations)
  urls="$coatlioan"
  ;;
ddoti-*:operations)
  urls="$ddotioan"
  ;;
colibri-*:operations)
  urls="$colibrioan $colibrilam"
  ;;
*-*:observations)
  urls="$alerts"
  ;;
*-*:alerts)
  urls="$alerts"
  ;;
*-*:test)
  urls="$test"
  ;;
*)
  echo 2>&1 "$program: error: chat is not configure for category $category on $(uname -n)."
  exit 1
  ;;
esac

if test -z "$urls"
then
  exit 0
fi

#url="https://chat.googleapis.com/v1/spaces/AAAALqR-TN0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=H4Mc4xQFoOAIsTvj0v1l15EwEqPaHY8ZUWgzGoqtQ8M"

case "$url" in
*mattermost*)
  if ! curl -s -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$source: $message\"}" $url >/dev/null
  then
    echo 2>&1 "$program: error: API call failed."
    exit 1
  fi
  ;;
*googleapis*)
  if ! curl -s -X POST -H "Content-Type: application/json" -d "{\"text\": \"$source: $message\"}" $url >/dev/null
  then
    echo 2>&1 "$program: error: API call failed."
    exit 1
  fi
  ;;
esac

exit 0
