#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-P priority] [-U URL] [-s subject] to message"
  exit 1
}

optstring=s:P:U:
subject=""
priority=0
url=""
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -s)
    subject="$2"
    shift 2
    ;;
  -P)
    priority="$2"
    shift 2
    ;;
  -U)
    url="$2"
    shift 2
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 2
then
  usageerror
fi
to="$1"
message="$2"

case $(uname -n) in
coatli-*)
  from=abps4xgknzg4j9atufnjbnhkb68gc3
  ;;
colibri-*)
  from=af9kucdjg9h8mz5qkczoxkcff8eph4
  ;;
ddoti-*)
  from=a8unfz1ihyc1kgkcbnbmrb26g4fynf
  ;;
*)
  echo 2>&1 "$program: error: invalid host \"$$(uname -n)\"."
  exit 1  
  ;;
esac

case $(uname -n):$to in
*:alan)
  to=uopAQF3pQRWhpJNCQgd2q8tGKDZRjW
  ;;
coatli-*:emergency)
  to=g7aded162wnz8gy82owkju5t5c7op5
  ;;
colibri-*:emergency)
  to=gp2n8mdxhgeygwzmsmwt8b6hdhzeg3
  ;;
ddoti-*:emergency)
  to=g3omst54iqohudou2h69yi7eb75iht
  ;;
grb-group)
  to=g7i8cm37qhqhef3xcd8kkkgshgwsyg
  ;;
gw-group)
  to=gphngipidum2tto8xg69zz9cgibcja
  ;;
*)
  echo 2>&1 "$program: error: invalid recipient \"$to\"."
  exit 1  
  ;;
esac

case $priority in
emergency)
  priority=2
  ;;
high)
  priority=1
  ;;
normal)
  priority=0
  ;;
low)
  priority=-1
  ;;
lowest)
  priority=-2
  ;;
*)
  echo 2>&1 "$program: error: invalid priority \"$priority\"."
  exit 1  
  ;;
esac

if ! curl -s \
  --form-string "token=$from" \
  --form-string "user=$to" \
  --form-string "priority=$priority" \
  --form-string "retry=60" \
  --form-string "expire=86400" \
  --form-string "title=$subject" \
  --form-string "message=$message" \
  --form-string "url=$url" \
  https://api.pushover.net/1/messages.json >/dev/null
then
  echo 2>&1 "$program: error: API call failed."
  exit 1
fi

exit 0
