#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: sendpushover 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-s subject] [-P priority] [-U URL] to"
  exit 1
}

optstring=s:P:U:
subject=""
priority=0
url=""
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -s)
    subject="$2"
    shift 2
    ;;
  -P)
    priority="$2"
    shift 2
    ;;
  -U)
    url="$2"
    shift 2
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 1
then
  usageerror
fi
to="$1"
body=$(cat)

case $(uname -n) in
ddotioan-*)
  from=a8unfz1ihyc1kgkcbnbmrb26g4fynf
  ;;
coatlioan-*)
  from=a211448fi9nio3gpj731v2red8o4nc
  ;;
esac

case $to in
  alan)
    to=uopAQF3pQRWhpJNCQgd2q8tGKDZRjW
    ;;
  grb-group)
    to=g7i8cm37qhqhef3xcd8kkkgshgwsyg
    ;;
  gw-group)
    to=gphngipidum2tto8xg69zz9cgibcja
    ;;
esac

case $priority in
emergency)
  priority=2
  ;;
high)
  priority=1
  ;;
normal)
  priority=0
  ;;
low)
  priority=-1
  ;;
lowest)
  priority=-2
  ;;
esac

if ! curl -s \
  --form-string "token=$from" \
  --form-string "user=$to" \
  --form-string "priority=$priority" \
  --form-string "retry=60" \
  --form-string "expire=86400" \
  --form-string "title=$subject" \
  --form-string "message=$body" \
  --form-string "url=$url" \
  https://api.pushover.net/1/messages.json >/dev/null
then
  echo 2>&1 "$program: error: API call failed."
  exit 1
fi

exit 0
