#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: startserver 3613 2020-06-20 20:21:43Z Alan $

########################################################################

# Copyright © 2010, 2011, 2012, 2013, 2014, 2016, 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

libexecdir="$tcsprefix/libexec/tcs"
program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-d] [--] servername [...]"
  echo 1>&2 "usage: $program [-d] [-f] [--] servername"
  echo 1>&2 "usage: $program [-d] [-a] [--]"
  exit 1
}

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case "$host" in
ratiroan-services)
  allargs="log 1 html gcntan"
  ;;
ratiroan-control)
  allargs="cryostat sensors power weather 1 target 1 moon sun 1 covers dome inclinometers lights secondary shutters 1 mount 1 nefinder sefinder 1 guider 1 telescope instrument 1 executor selector supervisor"
  ;;
ratiroan-detectors)
  allargs="C0 C1"
  ;;
ratiroan-tcs-a)
  allargs="C2 C3"
  ;;
coatlioan-control)
  allargs="sensors power weather 1 target 1 moon sun 1 secondary enclosure mount 1 telescope instrument 1 executor selector supervisor"
  ;;
coatlioan-services)
  allargs="log 1 html gcntan"
  ;;
coatlioan-a0)
  allargs=""
  ;;
coatlioan-c0)
  allargs="lights heater"
  ;;
coatlioan-e1)
  allargs="C0"
  ;;
ddotioan-control)
  allargs="sensors power weather 1 target 1 moon sun 1 enclosure mount 1 telescope instrument 1 executor selector supervisor"
  ;;
ddotioan-services)
  allargs="log 1 html gcntan"
  ;;
ddotioan-a0)
  allargs=""
  ;;
ddotioan-c0)
  allargs="lights heater"
  ;;
ddotioan-d1)
  allargs="C0"
  ;;
ddotioan-e1)
  allargs="C1"
  ;;
ddotioan-d2)
  allargs="C2"
  ;;
ddotioan-e2)
  allargs="C3"
  ;;
ddotioan-d3)
  allargs="C4"
  ;;
ddotioan-e0)
  allargs="C5"
  ;;
colibricito)
  allargs="log 2 html 1 target 1 moon sun"
  ;;
colibricu-services)
  allargs="log 1 html"
  ;;
colibricu-control)
  allargs="sensors power weather 1 target 1 moon sun 1 telescope instrument 1 executor selector"
  ;;
colibricu-detectors)
  allargs="C0"
  ;;
johnsoncu-control)
  allargs="log 1 html gcntan 1 target 1 moon sun sensors weather C0 1 telescope instrument 1 executor selector supervisor"
  ;;
coatlicu-control)
  allargs="log 1 html 1 target 1 moon sun sensors weather C0 1 telescope 1 selector"
  ;;
test-ubuntu-18)
  allargs="log 1 html gcntan 1 target 1 moon sun sensors weather C0 1 telescope instrument 1 executor selector supervisor"
  ;;
test-ubuntu-server-14)
  allargs="lights heater"
  ;;
test-minnowboard-14)
  allargs="lights heater"
  ;;
esac

optstring=adf
all=false
debug=false
foreground=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  -d)
    debug=true
    shift 1
    ;;
  -f)
    foreground=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift

if $all && $foreground
then
  usageerror
elif $all && test $# != 0
then
  usageerror
elif ! $all && test $# = 0
then
  usageerror
elif $foreground && test $# != 1
then
  usageerror
fi

if $all
then
  set -- $allargs
fi

for arg in "$@"
do
  case $arg in
  [0-9]*)
    sleep $arg
    ;;
  *)
    server=${arg}
    fullserver="$libexecdir"/${server}server
    pids=$(pgrep -u root -f $fullserver)
    if test -z "$pids"
    then
      if test -x $fullserver
      then
        if $foreground
        then
          TCSLOGDEBUG=$debug TCSLOGTOSTDERR=true $fullserver
        else
          TCSLOGDEBUG=$debug nohup $fullserver >/dev/null 2>&1 &
          printf '%5d   %s\n' $! $arg
        fi
      else
        echo 1>&2 "$program: error: invalid server \"$server\"."
        exit 1
      fi
    fi
    ;;
  esac
done

exit 0
