#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2010, 2011, 2012, 2013, 2014, 2016, 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

libexecdir="$tcsprefix/libexec/tcs"
program="tcs $(basename "$0")"

sudo -v

usageerror () {
  echo 1>&2 "usage: $program [--] servername [...]"
  echo 1>&2 "usage: $program [-a] [--]"
  echo 1>&2 "usage: $program [-A] [--]"
  exit 1
}

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case "$host" in
coatli-control)
  allargs="sensors power supervisor watchdog selector executor telescope mount enclosure secondary seeing weather sun moon target html"
  ALLARGS="gcntan"
  ;;
coatli-instrument)
  allargs="instrument C0"
  ALLARGS=""
  ;;
coatli-platform)
  allargs="heater lights"
  ALLARGS=""
  ;;
ddoti-control)
  allargs="sensors power supervisor watchdog selector executor instrument telescope mount enclosure weather sun moon target html"
  ALLARGS="gcntan"
  ;;
ddoti-platform)
  allargs="heater lights"
  ALLARGS=""
  ;;
ddoti-detectors0)
  allargs="C0 C2 C4"
  ALLARGS=""
  ;;
ddoti-detectors1)
  allargs="C1 C3 C5"
  ALLARGS=""
  ;;
colibri-control)
  allargs="supervisor watchdog selector executor telescope lights louvers fans mount secondary covers dome telescopecontroller sun moon target weather plc power seeing sensors html"
  ALLARGS="gcntan"
  ;;
colibri-instrument)
  allargs="instrument C2 C1 C0"
  ALLARGS=""
  ;;
tequila-dectector)
  allargs="C0 log"
  ALLARGS=""
  ;;
*)
  allargs="supervisor watchdog selector executor instrument telescope C1 C0 seeing weather sensors sun moon target html log"
  ALLARGS=""
  ;;
esac

optstring=aA
all=false
ALL=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  -A)
    ALL=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift

if $all && $ALL
then
  usageerror
elif ($all || $ALL) && test $# != 0
then
  usageerror
elif ! ($all || $ALL) && test $# = 0
then
  usageerror
fi

if $all
then
  set -- $allargs
fi
if $ALL
then
  set -- $allargs $ALLARGS
fi

for arg in "$@"
do
  fullserver="$libexecdir"/${arg}server
  pids=$(pgrep -u root -f $fullserver)
  if test ! -z "$pids"
  then
    sudo kill $pids
  fi
  pids=$(pgrep -u root -f $fullserver)
  if test ! -z "$pids"
  then
    sudo kill -KILL $pids
  fi
done
