#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: stopserver 3613 2020-06-20 20:21:43Z Alan $

########################################################################

# Copyright © 2010, 2011, 2012, 2013, 2014, 2016, 2017, 2018, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

libexecdir="$tcsprefix/libexec/tcs"
program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [--] servername [...]"
  echo 1>&2 "usage: $program [-a] [--]"
  exit 1
}

host=$(uname -n | sed 's/\..*//' | tr '[A-Z]' '[a-z]')
case "$host" in
ratiroan-services)
  allargs="gcntan html log"
  ;;
ratiroan-control)
  allargs="supervisor selector executor instrument telescope guider sefinder nefinder mount shutters secondary lights inclinometers dome covers weather moon sun target power sensors cryostat"
  ;;
ratiroan-detectors)
  allargs="C1 C0"
  ;;
ratiroan-tcs-a)
  allargs="C2 C3"
  ;;
coatlioan-control)
  allargs="sensors power supervisor selector executor instrument telescope mount enclosure secondary weather sun moon target"
  ;;
coatlioan-services)
  allargs="gcntan html log"
  ;;
coatlioan-a0)
  allargs=""
  ;;
coatlioan-c0)
  allargs="heater lights"
  ;;
coatlioan-e1)
  allargs="C0"
  ;;
ddotioan-services)
  allargs="gcntan html log"
  ;;
ddotioan-control)
  allargs="sensors power supervisor selector executor instrument telescope mount enclosure weather sun moon target"
  ;;
ddotioan-a0)
  allargs=""
  ;;
ddotioan-c0)
  allargs="heater lights"
  ;;
ddotioan-d1)
  allargs="C0"
  ;;
ddotioan-e1)
  allargs="C1"
  ;;
ddotioan-d2)
  allargs="C2"
  ;;
ddotioan-e2)
  allargs="C3"
  ;;
ddotioan-d3)
  allargs="C4"
  ;;
ddotioan-e0)
  allargs="C5"
  ;;
colibricito)
  allargs="sun moon target html log"
  ;;
colibricu-services)
  allargs="html log"
  ;;
colibricu-control)
  allargs="selector executor instrument telescope weather sun moon target power sensors"
  ;;
colibricu-detectors)
  allargs="C0"
  ;;
johnsoncu-control)
  allargs="supervisor selector executor instrument telescope C0 weather sensors sun moon target gcntan html log"
  ;;
coatlicu-control)
  allargs="weather sensors sun moon target html log"
  ;;
test-ubuntu-18)
  allargs="supervisor selector executor instrument telescope C0 weather sensors sun moon target gcntan html log"
  ;;
test-ubuntu-server-14)
  allargs="heater lights"
  ;;
test-minnowboard-14)
  allargs="heater lights"
  ;;
esac

optstring=a
all=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift

if $all && test $# != 0
then
  usageerror
elif ! $all && test $# = 0
then
  usageerror
fi

if $all
then
  set -- $allargs
fi

for arg in "$@"
do
  fullserver="$libexecdir"/${arg}server
  pids=$(pgrep -u root -f $fullserver)
  if test ! -z "$pids"
  then
    kill $pids
  fi
done
