#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

# $Id: submitgcnnotice 3562 2020-05-22 20:04:34Z Alan $

########################################################################

# Copyright © 2013, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

subject="$@"

prefix=/tmp/submitgcnnotice-$$
rm -f $prefix.*

cat >$prefix.txt

case $(file $prefix.txt) in
*UTF-8*)
  mv $prefix.txt $prefix.txt.utf-8
  iconv -f UTF-8 -t ISO-8859-1 <$prefix.txt.utf-8 >$prefix.txt
  rm -f $prefix.txt.utf-8
  ;;
*ASCII*)
  ;;
*ISO-8859*)
  ;;
*)
  echo 1>&2 "error: body is not encoded in a recognized encoding."
  rm -f $prefix.*
  exit 1
  ;;
esac

case $(id -un) in
nrbutler)
  address="Nat Butler <natbutler@asu.edu>"
  ;;
owen)
  address="Owen Littlejohns <olittlej@asu.edu>"
  ;;
ofox)
  address="Ori Fox <ofox@berkeley.edu>"
  ;;
alan)
  address="Alan Watson <alan@astro.unam.mx>"
  ;;
wlee)
  address="William Lee <wlee@astro.unam.mx>"
  ;;
*)
  echo 1>&2 "error: unregistered user \"$(id -un)\"."
  rm -f $prefix.*
  exit 1
  ;;
esac

(
  echo "From: $address"
  echo "To: $address"
  echo "Subject: $subject"
  echo "MIME-Version: 1.0"
  echo "Content-Type: text/plain; charset=\"iso-8859-1\""
  echo "Content-Transfer-Encoding: quoted-printable"
  echo
  qprint -e $prefix.txt
) |
sendmail -t
  
rm -f $prefix.*

exit
