#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2015, 2016, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin
export LC_ALL=C

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-a]"
  exit 1
}

optstring=a
all=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

mkdir -p "$tcsprefix"/var/tcs/weather-a
rsync -a rsync://132.248.4.66/weather/Archive/. "$tcsprefix"/var/tcs/weather-a/.

# Station b failed in 2023-02.
#mkdir -p "$tcsprefix"/var/tcs/weather-b
#rsync -a rsync://132.248.4.141/weather/Archive/. "$tcsprefix"/var/tcs/weather-b/.

mkdir -p "$tcsprefix"/var/tcs/weather
cd "$tcsprefix"/var/tcs/weather
(
  ls "$tcsprefix"/var/tcs/weather-a
  #ls "$tcsprefix"/var/tcs/weather-b
) | 
sort -ur | 
grep '^ARC-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].txt$' |
if $all 
then
  cat
else
  head -7
fi |
while read file
do
  # Give priority to weather-a.
  (
    (
      #test -f "$tcsprefix"/var/tcs/weather-b/"$file" && head --lines=2 "$tcsprefix"/var/tcs/weather-b/"$file"
      test -f "$tcsprefix"/var/tcs/weather-a/"$file" && head --lines=2 "$tcsprefix"/var/tcs/weather-a/"$file"
    ) | head --lines=2
    (
      #test -f "$tcsprefix"/var/tcs/weather-b/"$file" && tail --lines=+3 "$tcsprefix"/var/tcs/weather-b/"$file"
      test -f "$tcsprefix"/var/tcs/weather-a/"$file" && tail --lines=+3 "$tcsprefix"/var/tcs/weather-a/"$file"
    ) |
    sort -u -k1,2
  ) >"$file".tmp.$$
  if ! cmp -s "$file".tmp.$$ "$file"
  then
    mv -f "$file".tmp.$$ "$file"
  else
    rm -f "$file".tmp.$$
  fi
done
rm -rf weather.tmp.*

