#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

# $Id: updateweatherfiles-satino 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin
export LC_ALL=C

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program"
  exit 1
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

mkdir -p "$tcsprefix"/var/tcs/weather
cd "$tcsprefix"/var/tcs/weather

version="b.0"

weatherstatus=""
generalstatus=""
while test -z "$weatherstatus" || test -z "$generalstatus"
do
  seconds=$(date -u "+%s")
  weatherstatus=$(
    echo "WeatherStatus" |
    nc -w 1 192.168.100.28 200 | 
    tr -d '\r' |
    sed 's/;$//;s/;/ /g'
  )
  generalstatus=$(
    echo "GeneralStatus" |
    nc -w 1 192.168.100.28 200 | 
    tr -d '\r' |
    sed 'h;s/[^;]*;//;s/./& /g;x;s/;.*/ /;G' |
    tr -d '\n'
  )
done

timestamp=$(date -u --date=@$seconds "+%F %T")
date=$(date -u --date=@$seconds "+%F")

echo "$version $timestamp $weatherstatus $generalstatus" >>$date.txt
