#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2015, 2016, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################
export LC_ALL=C

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [-a]"
  exit 1
}

optstring=a
all=false
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

mkdir -p "$tcsprefix"/var/tcs/seeing-a
rsync -a rsync://132.248.4.160:16073/seeing/qhyc/data/ "$tcsprefix"/var/tcs/seeing-a/

mkdir -p "$tcsprefix"/var/tcs/seeing-b
rsync -a rsync://132.248.4.160:16073/seeing/sbig/data/ "$tcsprefix"/var/tcs/seeing-b/
