#!/bin/sh
########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2015, 2016, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin
export LC_ALL=C

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program"
  exit 1
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  -a)
    all=true
    shift 1
    ;;
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

sudo mkdir -p "$tcsprefix"/var/tcs/iers
cd "$tcsprefix"/var/tcs/iers

for bulletin in A B C D
do
  # curl -k is necessary because Ubuntu 16.04 has out-of-date certificates.
  if sudo curl -k -q -s -o bulletin$bulletin.txt.tmp https://datacenter.iers.org/data/latestVersion/bulletin$bulletin.txt 
  then
    sudo mv bulletin$bulletin.txt.tmp bulletin$bulletin.txt
  else
    tcs log "$program" warning "unable to update bulletin $bulletin."
  fi
done
