#!/bin/sh
########################################################################

# This file is part of the RATTEL telescope control system.

# $Id: updatelocalsensorsfiles 3461 2020-03-08 15:54:15Z Alan $

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-getopt/bin:/bin:/usr/bin:/usr/local/bin

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program"
  exit 1
}

optstring=
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 0
then
  usageerror
fi

mkdir -p "$tcsprefix"/var/tcs/sensors/local
cd "$tcsprefix"/var/tcs/sensors/local

update () {
  mkdir -p "$(dirname "$1")"
  cat >"$1-tmp"
  mv -f "$1-tmp" "$1"
}

uptime | sed 's/,//g' | awk '{ print $(NF-2); }' | update load

df "$tcsprefix"/var/tcs/ | sed 's/%//g' | awk 'NR == 2 { printf("%.2f\n", $5 / 100.0); }' | update disk-space-used

mkdir -p ow
for device in $(owdir | grep '/[0-9]')
do
  mkdir -p ow/$device
  touch ow/$device
  for file in \
    temperature \
    HIH4000/humidity \
    VAD \
    EDS0068/humidity \
    EDS0068/light \
    EDS0068/pressure \
    EDS0068/temperature
  do
    value=$(owread $device/$file 2>&-)
    if test ! -z "$value"
    then
      mkdir -p $(dirname ow/$device/$file)
      touch $(dirname ow/$device/$file)
      echo $value >ow/$device/$file
    fi
  done
done

exit 0
