#!/bin/sh

########################################################################

# This file is part of the UNAM telescope control system.

########################################################################

# Copyright © 2013, 2014, 2017, 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

program="tcs $(basename "$0")"

usageerror () {
  echo 1>&2 "usage: $program [--] identifier fitspath exposuretime readmode"
  exit 1
}

optstring=""
if ! getopt -qQ -- "$optstring" "$@"
then
  usageerror
fi
eval set -- "$(getopt -q -- "$optstring" "$@")"
while test "$1" != "--"
do
  case "$1" in
  *)
    usageerror
    ;;
  esac
done
shift
if test $# != 4
then
  usageerror
fi

identifier="$1"
fitspath="$2"
exposuretime="$3"
readmode="$4"

rts2-scriptexec -o "$fitspath.tmp" -d $identifier -s "n_reads=$readmode E $exposuretime" >/dev/null 2>&1
mv -f "$fitspath.tmp" "$fitspath"
exit 0

python /home/cklein/HXRGss_take_fowler_$identifier.py $readmode $exposuretime >/dev/null 2>&1
case $identifier in
C2)
  disk=/data1
  ;;
C3)
  disk=/data2
  ;;
esac
dir=$(ls $disk/H2RG*/FSRamp/ | tail -1)
path=$(echo $disk/H2RG*/FSRamp/$dir/Result/CDSResult.fits)
cp "$path" "$fitspath.tmp"
mv -f "$fitspath.tmp" "$fitspath"
exit 0

