#!/bin/sh

# $Id: alertscript-project-ddotioan 3373 2019-10-30 15:09:02Z Alan $

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

type="$1"
eventidentifier="$2"
targetidentifier="$3"

timestamp="$(date +"%Y-%m-%d %H:%M.%S")"

priority=""
case $type in
lvc*)
  priority="emergency"
  url="https://gracedb.ligo.org/superevents/$eventidentifier"
  group="gw-group"
  ;;
fermilat*)
  priority="emergency"
  url="https://gcn.gsfc.nasa.gov/other/$targetidentifier.fermi"
  group="grb-group"
  ;;
fermi*)
  priority="normal"
  url="https://gcn.gsfc.nasa.gov/other/$targetidentifier.fermi"
  group="grb-group"
  ;;
swift*)
  priority="normal"
  url="https://gcn.gsfc.nasa.gov/other/$targetidentifier.swift"
  group="grb-group"
  ;;
esac

if test "$priority" != ""
then
  echo "$timestamp: DDOTI/OAN has received a $type GCN Notice for $eventidentifier (target $targetidentifier)." |
  sendpushover \
    -P "$priority" \
    -U "$url" \
    -s "DDOTI/OAN $identifier: $type" \
    "$group"
fi

exit 0
