#!/bin/sh

# $Id: alertscript-project-ratiroan 3522 2020-03-15 23:02:59Z Alan $

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

name="$1"
origin="$2"
identifier="$3"
type="$4"

timestamp="$(date +"%Y-%m-%d %H:%M.%S")"

priority=""
case $origin in
swift)
  priority="normal"
  url="https://gcn.gsfc.nasa.gov/other/$blockidentifier.swift"
  group="grb-group"
  ;;
fermi)
  priority="normal"
  url="https://gcn.gsfc.nasa.gov/other/$blockidentifier.fermi"
  group="grb-group"
  ;;
lvc)
  priority="normal"
  url="https://gracedb.ligo.org/superevents/$eventidentifier"
  group="gw-group"
  ;;
esac

if test "$priority" != ""
then
  echo "$timestamp: TEST has received a $origin alert for $name (identifier $identifier type $type)." |
  $tcsprefix/bin/tcs sendpushover \
    -P "$priority" \
    -U "$url" \
    -s "TEST: $origin $type alert for $name" \
    "$group"
fi

exit 0
