#!/bin/sh

########################################################################

# Copyright © 2019 Alan M. Watson <alan@astro.unam.mx>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

########################################################################

name="$1"
origin="$2"
identifier="$3"
type="$4"

timestamp="$(date +"%Y-%m-%d %H:%M.%S")"

priority=""
case $type in
lvc*)
  priority="normal"
  url="https://gracedb.ligo.org/superevents/$identifier"
  group="gw-group"
  ;;
fermilat*)
  priority="emergency"
  url="https://gcn.gsfc.nasa.gov/other/$identifier.fermi"
  group="grb-group"
  ;;
fermi*)
  priority="emergency"
  url="https://gcn.gsfc.nasa.gov/other/$identifier.fermi"
  group="grb-group"
  ;;
swift*)
  priority="emergency"
  url="https://gcn.gsfc.nasa.gov/other/$identifier.swift"
  group="grb-group"
  ;;
hawc*)
  priority="normal"
  url="https://gcn.gsfc.nasa.gov/amon_hawc_events.html"
  group="grb-group"
  ;;
icecubecascade*)
  priority="normal"
  url="https://bacodine.gsfc.nasa.gov/amon_icecube_cascade_events.html"
  group="grb-group"
  ;;
icecube*)
  priority="normal"
  url="https://bacodine.gsfc.nasa.gov/amon_icecube_gold_bronze_events.html"
  group="grb-group"
  ;;
esac

if test "$priority" != ""
then
  echo "$timestamp: DDOTI has received a GCN Notice for $name ($origin/$type/$identifier)." |
  $tcsprefix/bin/tcs sendpushover \
    -P "$priority" \
    -U "$url" \
    -s "DDOTI $name" \
    "$group"
fi

exit 0
