#!/bin/sh

srcdir=$(dirname $0)

binning=$1

case $binning in
1)
  size=149360
  nx=1536
  ny=1536
  sx0=0
  sy0=54
  ;;
2)
  size=37400
  nx=768
  ny=768
  sx0=0
  sy0=26
  ;;
4)
  size=9408
  nx=384
  ny=384
  sx0=0
  sy0=13
  ;;
esac

set -- $(ls -s | awk -v size=$size '$1 ==size { print $2; }')

for ix in 0 1 2 3
do
  for iy in 0 1 2 3
  do
    sx=$(expr $sx0 + $ix "*" $nx)
    sy=$(expr $sy0 + $iy "*" $ny)
    section="[$(expr $sx + 1):$(expr $sx + $nx),$(expr $sy + 1):$(expr $sy + $ny)]"
    echo 1>&2 $ix $iy $sx $sy $nx $ny $section
    echo $ix
    echo $iy
    for file in "$@"
    do
      printf ' %s' $(fitsheadervalue SFCPS $file)
    done
    printf '\n'
    for file in "$@"
    do
      printf ' %s' $(fitsfwhm -A -s "$section " $file | awk '{ print $1; }')
    done
    printf '\n'
  done
done |
(
  cd $srcdir
  sh mapfocus.tcl
)
