#!/bin/sh

NAGELFARDIR="$(dirname "$0")"
NAGELFARTCL="$NAGELFARDIR"/nagelfar131/nagelfar.tcl
NAGELFARHDR="$NAGELFARDIR"/header
NAGELFAROUT="$NAGELFARDIR"/out

find "$NAGELFARDIR"/../tcs -name "*.tcl" | 
xargs tclsh "$NAGELFARTCL" -header "$NAGELFARHDR" >/dev/null

tclsh "$NAGELFARTCL" "$NAGELFARHDR" "$@" 2>&1 |
sed '
  /^Checking file /d
  s/ Line  *//
' | tee "$NAGELFAROUT" | bbresults -p '(?P<file>.+?):(?P<line>\d+):\s+(?P<type>[WEN])\s+(?P<msg>.*)$'


