#!/bin/sh

if test $# == 0
then
  set -- $(git diff --name-only | grep "\.tcl$")
fi

NAGELFARDIR="$(dirname "$0")"
NAGELFARTCL="$NAGELFARDIR"/nagelfar131/nagelfar.tcl
NAGELFARHDR="$NAGELFARDIR"/header

find "$NAGELFARDIR"/../tcs -name "*.tcl" | 
xargs tclsh "$NAGELFARTCL" -header "$NAGELFARHDR" >/dev/null

tclsh "$NAGELFARTCL" "$NAGELFARHDR" "$@" 2>&1 |
sed '
  /^Checking file /d
  s/ Line  *//
'
